### PR TITLE
Add test for leading zeroes behaviour

### PR DESCRIPTION
**Pull request by sublimator**
#2

### CODE REVIEW

**Comment by dcousens** [comment]
This test looks entirely as expected,  what am I missing?

**Comment by sublimator** [comment]
`000F` by any standard hex decoder, would decode as 2 bytes, not 4

**Comment by sublimator** [comment]
It's a bit odd I agree asserting against, faulty but expected behaviour, if you were talking about that. I was told by a guy it's `what they did at google` so who was I to argue :)  I've done it that way since.

The beauty of the way this (bitcoin) packs in leading zeroes at least, is that it seems to require no padding, and there's a 1:1 encoding for any given value. It seems like you can take any random string of alphabet characters, and decode it into bytes, and re-encode it and you will get the same string. An interesting property anyway :)

**Comment by dcousens** [comment]
> I agree asserting against faulty but expected behaviour

It wasn't, but I agree with this sentiment.

> The beauty of the way this (bitcoin) packs in leading zeroes at least, is that it seems to require no padding, and there's a 1:1 encoding for any given value. It seems like you can take any random string of alphabet characters, and decode it into bytes, and re-encode it and you will get the same string. An interesting property anyway :)

I thought this was how it was supposed to work? :)

**Comment by sublimator** [comment]
Yeah, my point was '00F' and '000F' decode to the same thing in a normal
hex decoder, but they probably reencode to the latter... Whereas there
seems like a 1:1 mapping of string encoding to byte array when using
leading zero compression.

I'm a little confused as to whether you see any problem with decoding
'000F' to 4 bytes from a hex alphabet rather than 2. The failing base 2
tests seemed to indicate you were. But I can't recall the details from
memory. Out, on mobile atm

I think the behaviour should just be explained. Not all people maybe be
familiar with the way it works and it could be surprising.

On mobile atm. Catch ya ron :)


On 15 Jun 2015 14:42, "Daniel Cousens" <notifications@github.com> wrote:
>>
>> I agree asserting against faulty but expected behaviour
>
> It wasn't, but I agree with this sentiment.
>>
>> The beauty of the way this (bitcoin) packs in leading zeroes at least,
is that it seems to require no padding, and there's a 1:1 encoding for any
given value. It seems like you can take any random string of alphabet
characters, and decode it into bytes, and re-encode it and you will get the
same string. An interesting property anyway :)

**Comment by dcousens** [comment]
> I'm a little confused as to whether you see any problem with decoding
'000F' to 4 bytes from a hex alphabet rather than 2. The failing base 2
tests seemed to indicate you were. But I can't recall the details from
memory. Out, on mobile atm

That is possible, I have been context switching quite a bit today,  I'll make sense of the test cases when I can get around to them :)

**Comment by sublimator** [comment]
Cool. Touch base soon. Works for any  base58 bitcoin stuff now anyway :) So
thanks!

**Comment by dcousens** [comment]
No worries @sublimator I'll add you as a contributor so we can work on the same branches.

**Pull request closed without merging**
